/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CalculadoraArreglos;

import javax.swing.JOptionPane;

/**
 *
 * @author GatomanJuarez
 */
public class Interfaz extends javax.swing.JFrame {

    Metodos dos = new Metodos();

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        llenar = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        transpuesta = new javax.swing.JButton();
        rango = new javax.swing.JButton();
        determinante = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CALCULADORA DE MATRICES BY Gatoman");

        llenar.setText("Llenar matrices");
        llenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llenarMouseClicked(evt);
            }
        });
        llenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llenarActionPerformed(evt);
            }
        });

        suma.setText("Suma");
        suma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumaMouseClicked(evt);
            }
        });

        resta.setText("Resta");
        resta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaMouseClicked(evt);
            }
        });

        transpuesta.setText("Transpuesta");
        transpuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transpuestaMouseClicked(evt);
            }
        });

        rango.setText("Rango");
        rango.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rangoMouseClicked(evt);
            }
        });

        determinante.setText("Determinante");
        determinante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                determinanteMouseClicked(evt);
            }
        });

        jButton3.setText("Cramer");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton1.setText("Inversa 3x3");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Inversa 2x2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Reiniciar datos");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(llenar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(rango)
                                        .addGap(28, 28, 28)
                                        .addComponent(determinante))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(suma)
                                        .addGap(33, 33, 33)
                                        .addComponent(resta)
                                        .addGap(49, 49, 49)
                                        .addComponent(transpuesta)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(70, 70, 70)
                                .addComponent(jButton5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton2))
                        .addGap(32, 32, 32))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(llenar)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(suma)
                            .addComponent(resta)
                            .addComponent(transpuesta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rango)
                            .addComponent(determinante))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(20, 20, 20)
                        .addComponent(jButton2)
                        .addGap(33, 33, 33)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_llenarActionPerformed


    private void llenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llenarMouseClicked
        dos.borrardatosexixtentes();
        dos.llenar();
        dos.mostrar();
    }//GEN-LAST:event_llenarMouseClicked

    private void sumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaMouseClicked
        dos.borraroperaciones();
        dos.sumavector();
        System.out.println("La suma de los vectores es: ");
        dos.mostrarsuma();
    }//GEN-LAST:event_sumaMouseClicked

    private void restaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaMouseClicked
        dos.borraroperaciones();
        dos.restavector();
        System.out.println("La resta de los vectores es: ");
        dos.mostrarresta();
    }//GEN-LAST:event_restaMouseClicked

    private void transpuestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transpuestaMouseClicked
        dos.borraroperaciones();
        int opce = Integer.parseInt(JOptionPane.showInputDialog("Que vector quieres que se calcule la transpuesta"));
        dos.transpuesta(opce);
        dos.mostrartranspuesta();
    }//GEN-LAST:event_transpuestaMouseClicked

    private void determinanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_determinanteMouseClicked
        dos.borrar();
        int opcje = Integer.parseInt(JOptionPane.showInputDialog("Que vector quieres que se calcule la determinante"));
        dos.calculardeterminante(opcje);
    }//GEN-LAST:event_determinanteMouseClicked

    private void rangoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rangoMouseClicked
        dos.borrarrango();
        int opc = Integer.parseInt(JOptionPane.showInputDialog("Que vector quieres que se calcule el rango"));
        dos.borrar();
        int determinante = dos.calculardeterminante(opc);
        int rango1 = dos.calcularrango(opc);

        if (determinante != 0) {
            System.out.println("El rango de la matriz es: 3");
        } else if (rango1 != 0) {
            System.out.println("El rango de la matriz es: 2");
        } else {
            System.out.println("El rango de la matriz es: 1");
        }
    }//GEN-LAST:event_rangoMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        int op = 1;
        dos.metodoCramerllenar(op);
        dos.llenarcramerresult(op);
        dos.mostrarcramer();
        dos.borrar();
        int numero = dos.determinanteCramer();
        System.out.println("\n" + "La determinante es: " + numero + "\n");
        if (numero == 0) {
            JOptionPane.showInputDialog(null, "No se puede ralizar la inversa");
        } else {
            dos.cramer();
            System.out.println();
            dos.cramer2();
            System.out.println();
            dos.cramer3();
            System.out.println();
            dos.borrar();
            int une = dos.cramerdeter(numero);
            System.out.println("\n" + "El valor de x1 es: " + une + "\n");
            dos.borrar();
            int un = dos.cramerdeter2(numero);
            System.out.println("\n" + "El valor de x2 es: " + un + "\n");
            dos.borrar();
            int u = dos.cramerdeter3(numero);
            System.out.println("\n" + "El valor de x3 es: " + u + "\n");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int opcd = Integer.parseInt(JOptionPane.showInputDialog("Que vector quieres que se calcule su inversa"));
        int num = dos.calculardeterminante(opcd);

        if (num == 0) {
            System.out.println("No se puede ralizar la inversa");
        } else {
            dos.borrar();
            dos.borrarinversa();
            dos.borraroperaciones();
            dos.borrarrango();
            System.out.println(num);
            dos.transpuesta(opcd);
            dos.mostrartranspuesta();
            dos.inversa1();
            dos.inversa2();
            dos.inversa3(num);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        dos.inversamatriz2();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
dos.borrarinversa();
dos.borraroperaciones();
dos.borrarrango();
dos.borrar();
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton determinante;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton llenar;
    private javax.swing.JButton rango;
    private javax.swing.JButton resta;
    private javax.swing.JButton suma;
    private javax.swing.JButton transpuesta;
    // End of variables declaration//GEN-END:variables
}
